services:
  cinema_db:
    image: postgres:latest
    container_name: cinema_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - cinema_db

volumes:
  db_data:
